# NO JENKINS
FROM openjdk:8-jdk-alpine
MAINTAINER 54chi

RUN apk add --no-cache git openssh-client tar curl unzip bash ttf-dejavu coreutils tini procps

# From {version}-jdk-alpine these will be set (e.g. for 1.8)
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin

ENV ANT_VERSION 1.10.1
ENV MVN_VERSION=3.5.3
ENV SF_VERSION 40.0

# Changing to root
USER root

#INSTALLING MAVEN
RUN curl -sSL "https://apache.osuosl.org/maven/maven-3/${MVN_VERSION}/binaries/apache-maven-${MVN_VERSION}-bin.tar.gz" | tar -xzf - -C /usr/lib/  \
    && mv /usr/lib/apache-maven* /usr/lib/maven \
    && ln -s /usr/lib/maven/bin/mvn /usr/bin/mvn

#INSTALLING ANT
  RUN mkdir -p /var/ant_home
  ADD http://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.zip /var/ant_home/apache-ant-${ANT_VERSION}-bin.zip
  RUN unzip /var/ant_home/apache-ant-${ANT_VERSION}-bin.zip -d /var/ant_home && rm /var/ant_home/apache-ant-${ANT_VERSION}-bin.zip
  ENV ANT_HOME=/var/ant_home/apache-ant-${ANT_VERSION}
  ENV PATH=${PATH}:${ANT_HOME}/bin

#INSTALLING SALESFORCE ANT PLUGIN
  RUN mkdir ${ANT_HOME}/lib/x
  ADD https://gs0.salesforce.com/dwnld/SfdcAnt/salesforce_ant_${SF_VERSION}.zip ${ANT_HOME}/lib/x/salesforce_ant_${SF_VERSION}.zip
  RUN unzip ${ANT_HOME}/lib/x/salesforce_ant_${SF_VERSION}.zip -d ${ANT_HOME}/lib/x && cp ${ANT_HOME}/lib/x/ant-salesforce.jar ${ANT_HOME}/lib/ant-salesforce.jar && rm -rf ${ANT_HOME}/lib/x

# SOME CLEANING
  RUN rm -rf /var/cache/apk/* /tmp/*
  
ENV JAVA_OPTS="-Xmx4096m"
